/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://fn4k7w2a7jga7jiwkqtglmo75m.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AWS_IAM",
    "aws_appsync_apiKey": "da2-al7k2eepbfb35cr6nvmc53qswy",
    "aws_cognito_identity_pool_id": "us-east-1:39fff8a7-88b5-4b63-b07a-48a46014a8e2",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_8tncHkg7V",
    "aws_user_pools_web_client_id": "4kklctrcg7nkv1a8nvklpqonsf",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "huskysyncbucketc500b-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
